# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workcontainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('ccolumn', models.PositiveSmallIntegerField()),
                ('crow', models.PositiveSmallIntegerField()),
                ('cdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=255)),
                ('wcolumn', models.PositiveSmallIntegerField()),
                ('wrow', models.PositiveSmallIntegerField()),
                ('wdescription', models.TextField()),
            ],
        ),
    ]
