# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_slot', models.CharField(max_length=255)),
                ('source_well', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('destination_slot', models.CharField(max_length=255)),
                ('destination_well', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Workcontainer',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
